// app/layout.js

import "./globals.css";
import { Inter } from "next/font/google";

// ✅ Only using Inter (you were trying to use GeistMono, but it's not defined)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
